[package]
name = "sptc"
version = "0.1.2"
edition = "2021"
authors = ["golferjoe"]
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap-help = "1.3"
base64 = "0.22"
mime_guess = "2.0"
thiserror = "2.0"
colored = "3.0"
regex = "1.11"
